config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: 'tunes#index'
  resources :tunes do
    collection { get 'search' }
    collection { patch '/:id/increment_views', to: 'tunes#increment_views', as: 'tune' }
  end
  # Define your application routes per the DSL in http_s://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # unless Rails.env.production?
  #   namespace :anonymous do
  #     get 'show', :action => :show
  #   end
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tune.rb
# Model for youtube songs
class Tune < ActiveRecord::Base
  # == Constants ============================================================

  # == Attributes ===========================================================

  # == Extensions ===========================================================
  include PgSearch::Model
  # == Relationships ========================================================

  # == Validations ==========================================================
  validates :game_title, presence: true
  validates :song_title,
            presence: true,
            uniqueness: {
              scope: :game_title,
              message: 'This song has already been added.'
            }
  # has to accept only the video id for update purposes
  validates :youtube_video_id,
            presence: true,
            uniqueness: {
              message: 'This video has already been added.'
            },
            format: {
              with: %r{.*youtu.*[=/]([\w-]*)|[\w|-]{11}},
              message: 'Please check your youtube link.'
            }

  # == Scopes ===============================================================
  scope :by_date, -> { order(created_at: :desc) }
  scope :by_game, -> { order(:game_title) }
  scope :by_song, -> { order(:song_title) }
  scope :most_viewed, -> { order(views: :desc) }

  pg_search_scope :search,
                  against: %i[game_title song_title],
                  using: {
                    tsearch: {
                      prefix: true,
                      dictionary: 'english'
                    }
                  }

  # == Callbacks ============================================================
  before_save :extract_video_id_from_youtube_url
  # == Class Methods ========================================================

  # == Instance Methods =====================================================
  def extract_video_id_from_youtube_url
    # for update we just return what's already there
    return if youtube_video_id =~ /^[\w-]{11}$/

    self.youtube_video_id = youtube_video_id.match(%r{.*youtu.*[=/]([\w-]*)})[1]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # == Constants ============================================================

  # == Attributes ===========================================================

  # == Extensions ===========================================================
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # == Relationships ========================================================
  has_many :tunes
  
  # == Validations ==========================================================

  # == Scopes ===============================================================

  # == Callbacks ============================================================

  # == Class Methods ========================================================

  # == Instance Methods =====================================================
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :joke

  def joke
    if Rails.env.development?
      stub_request(:get, /icndb.com/)
        .to_return(status: 200, body: 'Chuck Norris is sleeping', headers: {})
    end

    @haar_joke = HaarJoke.create_joke
  end
end

app/controllers/tunes_controller.rb
# Actions for adding, removing and editing youtube songs.
class TunesController < ApplicationController
  require 'json'
  require 'open-uri'
  before_action :find_tune, only: %i[increment_views edit update destroy]

  def index
    @tunes = params[:sort].nil? ? Tune.by_date : tunes_sorted(params[:sort])
  end

  def search
    @tunes = Tune.search(params[:q])
    @hits = @tunes.count
  end

  def new
    @tune = Tune.new
  end

  def edit; end

  # def show
  #   @tune.views += 1
  #   @tune.save
  #   # respond_to do |format|
  #   #   format.html do
  #   #     flash[:alert] = 'JavaScript needs to be enabled to play videos.'
  #   #     redirect_to tunes_path
  #   #   end
  #   #   format.js
  #   # end
  # end

  def create
    @tune = Tune.new(tune_params)
    if @tune.save
      redirect_to tunes_path
    else
      flash[:alert] = 'Song not created.'
      render :new
    end
  end

  def update
    @tune.update(tune_params)
    if @tune.save
      redirect_to tunes_path
    else
      flash[:alert] = 'Song not updated.'
      render :edit
    end
  end

  def destroy
    @tune.delete
    redirect_to tunes_path
  end

  def increment_views
    @tune.views += 1
    render json: @tune if @tune.save
  end

  private

  def find_tune
    @tune = Tune.find(params[:id])
  end

  def tune_params
    params.fetch(:tune, {}).permit(:game_title, :song_title, :youtube_video_id)
  end

  def tunes_sorted(sort)
    sort.downcase!
    Tune.send(sort.to_sym)
  end
end

app/helpers/tunes_helper.rb
module TunesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Haar's House of Tunes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render partial: 'shared/banner', locals: {haar_joke: @haar_joke}%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <!--%= javascript_include_tag 'application' %-->
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <%= render partial: 'shared/head' %>
  <body>
    <%= render partial: 'shared/banner', locals: {haar_joke: @haar_joke}%>
    <%= render partial: 'shared/alerts' %>

    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-10 col-md-8">
          <div class="form-wrapper">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<% content_for(:title) do %>
  <%= "Haar's House of Tunes" %>
<% end %>
<div class="banner">
  <div class="banner-content">
    <div><h1 class="banner-header">Haar's House of Tunes</h1></div>
    <div><%= image_tag 'haar.png' %></div>
  </div>
</div>

<div class="wrapper-white">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <!-- Chuck Norris joke replaced with Haar -->
        <p class="text-center text-gray"><%= @haar_joke %></p>
      </div>
    </div>
  </div>
  <div class="text-right text-light-gray text-small padded-right">
    Jokes are not mine ("http://www.icndb.com/")
  </div>
</div>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <div>
      <h1 class="banner-header">Haar's House of Tunes</h1>
    </div>
    <div><%= image_tag 'haar.png' %></div>
  </div>
</div>
<div class="bg-light py-2">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 offset-sm-1">
        <!-- Chuck Norris joke replaced with Haar -->
        <p class="text-center text-gray"><%= haar_joke %></p>
      </div>
    </div>
  </div>
  <div class="text-end text-light-gray text-small pe-1">
    Jokes are not mine ("http://www.icndb.com/")
  </div>
</div>

app/views/shared/_head.html.erb
<head>
  <title><%= yield(:title) || "Haar's House of Tunes" %></title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>

app/views/tunes/_form.html.erb
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-6">
      <div class="card bg-light">
        <div class="card-body">
          <%= simple_form_for @tune do |f| %>
            <%= f.input :game_title%>
            <%= f.input :song_title%>
            <%= f.input :youtube_video_id%>
            <div class="d-flex justify-content-between">
              <%= link_to "Cancel", tunes_path, class: "btn btn-secondary w-100 me-2" %>
              <%= f.button :submit, class: "btn btn-primary w-100 ms-2" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tunes/_toolbar.html.erb
<!-- For larger views -->
<div class="toolbar d-none d-sm-none mb-5 d-md-flex align-items-center w-100">
  <div class="toolbar-left d-flex align-items-center">
    <div class="toolbar-label shadow me-2 text-light-gray">
      Sort all tunes
    </div>
    <div class="toolbar-filter-buttons d-flex">
      <%= form_tag(tunes_path, method: :get, class: "toolbar-link") do %>
        <%= hidden_field_tag(:sort, "by_game") %>
        <%= submit_tag("By Game", class: "btn btn-sm btn-info me-1") %>
      <% end %>
      <%= form_tag(tunes_path, method: :get, class: "toolbar-link") do %>
        <%= hidden_field_tag(:sort, "by_song") %>
        <%= submit_tag("By Song", class: "btn btn-sm btn-info me-1") %>
      <% end %>
      <%= form_tag(tunes_path, method: :get, class: "toolbar-link") do %>
        <%= hidden_field_tag(:sort, "most_viewed") %>
        <%= submit_tag("Most Viewed", class: "btn btn-sm btn-info me-1") %>
      <% end %>
    </div>
  </div>
  <div class="toolbar-center mx-2">
    <%= form_tag(search_tunes_path, method: "get", id: "search-form") do %>
      <div class="input-group input-group-sm">
        <%= text_field_tag :q, nil, placeholder: "Search song or game", class: "form-control" %>
        <%= button_tag(class: "btn btn-outline-light", id: "btn-search-submit") do %>
          <i class="bi bi-search" aria-hidden="true"></i>
        <%end %>
      </div>
    <% end %>
  </div>
  <div class="toolbar-end toolbar-link ms-auto">
    <%= link_to new_tune_path, class: "btn btn-sm btn-info" do %>
      <i class="bi bi-plus-lg" aria-hidden="true"></i> Add Song
    <% end %>
  </div>
</div>
<!-- For smaller views -->
<div class="d-md-none d-lg-none">
  <div class="btn-group" role="group">
    <!-- dropdown  -->
    <div class="btn-group" role="group">
      <button class="btn btn-sm btn-info dropdown-toggle" data-bs-toggle="dropdown">
        Sort
      </button>
      <ul class="dropdown-menu" aria-labelledby="sortOptions">
        <li>
          <%= link_to "By Game", tunes_path(@tunes, method: :get, sort:"by_game"), class: "dropdown-item text-white" %>
        </li>
        <li>
          <%= link_to "By Song", tunes_path(@tunes, method: :get, sort:"by_song"), class: "dropdown-item text-white" %>
        </li>
        <li>
          <%= link_to "Most Viewed", tunes_path(@tunes, method: :get, sort:"most_viewed"), class: "dropdown-item text-white" %>
        </li>
      </ul>
    </div>
    <button class="btn btn-sm btn-info dropdown-toggle" id="searchButtonMobile" data-bs-toggle="dropdown">
      <i class="bi bi-search" aria-hidden="true"></i> Search
    </button>
    <!-- Add song -->
    <%= link_to "Add Song", new_tune_path, class: "btn btn-sm btn-info" %>
  </div>
  <%= form_tag(search_tunes_path, method: "get", class: "invisible", id: "searchBoxMobile") do %>
    <div class="input-group">
      <div>
        <%= text_field_tag :q, nil, placeholder: "Search song or game", class: "form-control form-control-mobile search-field" %>
      </div>
      <div>
        <%= button_tag(class: "form-control form-control-mobile search-field btn btn-default", id: "btn-search-submit") do %>
          Go
        <%end %>
      </div>
    </div>
  <% end %>
</div>

app/views/tunes/_tune_collection.html.erb
<div class="row video-grid" data-controller="video">
  <% @tunes.each do |tune| %>
    <div class="col-xs-12 col-sm-4 video">
      <div class="video-container" id="container-<%= tune.youtube_video_id %>"/>
        <div class="video" id="youtube-placeholder-<%= tune.youtube_video_id %>">
          <button class='play-button hidden d-block' data-action="click->video#play"
            data-video-id-param="<%= tune.id%>"
            data-video-youtube-id-param="<%= tune.youtube_video_id%>" data-video-view-count-param="<%= tune.views %>">
            <span class="visually-hidden">Play</span>
          </button>
        </div>
        <div class="icon icon-relative-top-right d-flex">
          <%= link_to edit_tune_path(tune), class: "edit-button" do %>
            <i class="bi bi-pencil-square" aria-hidden="true"><span class="visually-hidden-focusable">Edit Song</span></i>
          <% end %>
          <%= link_to tune_path(tune), class: "delete-button", data: { turbo_confirm: "Are you sure you want to delete this tune?", turbo_method: :delete }  do %>
            <i class="bi bi-trash"><span class="visually-hidden-focusable">Delete Song</span></i>
          <% end %>
        </div>
        <% unless tune.game_title.blank? && tune.song_title.blank? %>
          <div class="caption">
            <div class="caption-text">
              <p><%= tune.game_title %> - <%= tune.song_title %></p>
            </div>
            <div class="caption-views text-end">
              <i class="bi bi-eye" aria-hidden="true"></i> <span data-video-target="viewCount" id="view-count-<%= tune.youtube_video_id %>"><%= tune.views %></span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/tunes/edit.html.erb
<%= render 'form' %>

app/views/tunes/index.html.erb
<% content_for(:title) do %>
  <%= "Haar's House of Tunes" %>
<% end %>
<div class="wrapper-default padded">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-10 offset-md-1">
        <%= render 'toolbar' %>
        <%= render 'tune_collection' %>
      </div>
    </div>
  </div>
</div>

app/views/tunes/new.html.erb
<%= render 'form' %>